#!/bin/bash

a() {
	echo "Installing busybox-static"
	local URL=""
	local ALPINE_ARCH=
	local ALPINE_MIRROR=http://mirror.xtom.com.hk/alpine
	local ALPINE_DIST=edge
	case $(uname -m) in
		x86_64)
			ALPINE_ARCH=x86_64
			;;
		aarch64)
			ALPINE_ARCH=aarch64
			;;
		armv7l)
			ALPINE_ARCH=armv7
			;;
	esac
	local BBSTATIC_VERSION="$(wget -q -O - ${ALPINE_MIRROR}/${ALPINE_DIST}/main/${ALPINE_ARCH}/APKINDEX.tar.gz | tar -Oxz | grep --text '^P:busybox-static$' -A1 | tail -n1 | cut -d: -f2)"
	local BBSTATIC_URL="${ALPINE_MIRROR}/${ALPINE_DIST}/main/${ALPINE_ARCH}/busybox-static-${BBSTATIC_VERSION}.apk"
	wget ${BBSTATIC_URL}-q -O - | tar -xz -C /usr/local bin/busybox.static  2>/dev/null
	chmod 755 /usr/local/bin/busybox.static
	echo "OK"

}
a
