#!/bin/sh

p=$(pwd)
p=$(realpath ${p})

rm -rf /build
mkdir -p /build

cd /build
git clone https://aur.archlinux.org/package-query.git --depth 1
cd package-query
makepkg -si --noconfirm
cp *.pkg.tar.zst ${p}/

cd /build
git clone https://aur.archlinux.org/yaourt.git --depth 1
cd yaourt
makepkg -si --noconfirm
cp *.pkg.tar.zst ${p}/

cd /
rm -rf /build
